### PR TITLE
Various cleanup

### PR DESCRIPTION
**Pull request by pstray**
Various cleanups:
Simpler, more robust reading of config file, including removal of all the "declare -i", some of which were just wrong.
Some more descriptive names, and simpler logic.
More quoteing of variables.
Inline expressions.
Added a (missing) sleep in the off-loop when led_pin is off.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thanks for taking the time to make this PR! It hasn't gone unnoticed. I've just been busy with 101 other things.  It's on my TODO list to test and merge.

**Review by ferrix — CHANGES_REQUESTED** [review]
The code itself becomes more highly readable and robust due to these changes, so functionally I am all for it. However, this patch introduces mixed indentation of spaces and tabs.

**Comment by pstray** [comment]
Fixed... replaced the last commit with one with just spaces and no tabs :)

**Review by ferrix — APPROVED** [review]
Works for me.

**Comment by ferrix** [comment]
Fixes #19

**Comment by Gadgetoid** [comment]
Thank you- this is brilliant work. I agree with @ferrix it's drastically cleaned up the code and made it easier to read. Much appreciated!

**Pull request merged**
